name: "Mandy site build."
description: ""
runs:
  using: "composite"
  steps:
    - name: "Installing Rust."
      uses: "actions-rs/toolchain@v1"
      with:
        toolchain: "stable"
    - name: "Install Mandy."
      shell: bash
      run: "cargo install --git https://github.com/angeldollface/mandy.git"
